### PR TITLE
Update OPTANO.Modeling to 3.9.2.537 (latest)

### PR DESCRIPTION
**Pull request by brianrourkeboll**
[This version](https://docs.optano.com/modeling/current/changelog.html#version-392-2021-12-10) of OPTANO.Modeling [includes a fix to the null reference exception bug](https://docs.optano.com/modeling/current/changelog.html#version-390-2021-11-15) introduced in OPTANO.Modeling 3.8.1.532 (which was itself referenced in #178 in an effort to fix [a _different_ OPTANO bug](https://docs.optano.com/modeling/current/changelog.html#version-381-2021-10-15)).

### CODE REVIEW

**Comment by matthewcrews** [comment]
I'll get this taken care of this evening

**Comment by matthewcrews** [comment]
@brianrourkeboll New version has been uploaded to NuGet. You should see it shortly.

**Comment by brianrourkeboll** [comment]
@matthewcrews It does look like 2.4.7 somehow changed the package's FSharp.Core dependency to be (= 5.0.0) instead of (≥ 5.0.1). I'm not sure whether that was due to the update to paket.lock made in this PR or, possibly, the way 2.4.7 was built/packaged.

For my update I just ran `dotnet paket update OPTANO.Modeling`. I don't _think_ I see anything in the diff to paket.lock above that would cause that change.

**Comment by matthewcrews** [comment]
@brianrourkeboll I'll get this fixed this evening. My apologies for the issue. I had some other things to fix as well.

Fake is not as up-to-date as Paket so that was likely the issue.

**Comment by matthewcrews** [comment]
New issue created to track this:
https://github.com/fslaborg/flips/issues/183

**Comment by brianrourkeboll** [comment]
@matthewcrews No worries! It builds and runs fine with FSharp.Core 6.0.1 in practice&mdash;there's just a `NU1608` warning from NuGet on restore.

**Comment by matthewcrews** [comment]
Yeah, still drives me crazy though. I like changing warnings into errors in the compiler settings so this definitely feels like a step backward 😂

**Pull request merged**
